version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/employeemanagement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      - 'POSTGRES_DB=employee_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=adm'

volumes:
  postgres-data:
