version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/employeemanagement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://0.0.0.0:5432/employee_db
      SPRING_DATASOURCE_USERNAME: adm
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - 'POSTGRES_DB=employee_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=adm'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
